(ql:quickload "ltk")
(in-package :ltk)
(load "./math/general.lisp")
(load "./generate-prime/miller-rabin.lisp")
(load "./generate-prime/generate-prime.lisp")
(load "./RSA/RSA.lisp")
(load "./digital-signature/digital-signature.lisp")
(load "./check-friend/check-friend.lisp")
(load "./gui.lisp")


(rsa-get-key "MyKey")
(rsa-get-key "BobKey")
;;(sig-generate-id "eddie")
;;(format t "~%~%TEST ~A~%~%" (sig-check-id))
;;(setf sig-test (sig-encrypt-rsa-pss "Andy"))
;;(sig-decrypt-rsa-pss "Andy" sig-test)
(cf-sig-friend)
(cf-sig-friend "Bobfriend")
(cf-sig-check-same-friend "sig-myfriend" "sig-Bobfriend" "BobKey")

(gui)
